### PR TITLE
3.15.8 cursor bugfix

### PR DESCRIPTION
**Pull request by redhog**
Resolves https://github.com/CartoDB/cartodb.js/issues/911

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by redhog** [comment]
@javisantana Could you take a look at this PR too?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by rubenmoya** [comment]
As stated in https://github.com/CartoDB/carto.js/issues/1298#issuecomment-404193738, cartodb.js v3 is not under active development. Closing this.

**Pull request closed without merging**
