### PR TITLE
tile aggregation cluster example

### PR DESCRIPTION
**Pull request by oriolbx**

### CODE REVIEW

**Comment by oriolbx** [comment]
Is there something missing or wrong in the example?

**Comment by VictorVelarde** [comment]
I have found this "lost" question about some carto.js examples
Please add it to RT @CartoDB/rt-managers

**Comment by Jesus89** [comment]
This PR adds a new example. If we want to merge it I can fix minor issues like the title and format and merge it.

cc @VictorVelarde

**Comment by VictorVelarde** [comment]
Let's do it!

**Pull request merged**
