### PR TITLE
add hexagon aggregation example

### PR DESCRIPTION
**Pull request by oriolbx**
Add Leaflet and Gmaps example of point aggregation with hexagon aggregation

### CODE REVIEW

**Comment by oriolbx** [comment]
done @ivanmalagon :)

**Comment by oriolbx** [comment]
Ok, this is not on the rest of examples, that means that we would need to modify all existing examples with comments for each block of code, right?

**Comment by ivanmalagon** [comment]
I've merged this PR but it won't be published to docs until another PR with code gets merged.

We did a change to avoid differences between docs and code and we need to publish a tag in order to reflect changes in docs.

Since we're in active development of v4.1 this isn't a problem. We're going to merge code these days.

**Comment by oriolbx** [comment]
Great! Thanks for the info! :)

**Pull request merged**
